# Site settings
title: Blog | RealChainğŸ®Ê• â€¢á´¥â€¢Ê”
email: realchainlife@protonmail.com
description: "Decentralized protocols, Distributed Systems, and more, by Sonia John"
baseurl: "/blog"
url: ""
future: true

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
paginate: 10

# Gems
gems: [jekyll-paginate]
